### ISSUE TITLE
Personal Podcast aggregation solution

### ISSUE THREAD

**Issue by elreydetoda** [MichaelTunnell/dln-rss-merge#1]
Hey @MichaelTunnell, 

I heard about the all shows feed one of the DLN shows, and I love having all of them aggregated! While it didn't change much for me (more on that in a sec), it did make a couple less show names that I have to type out (since I listen to quite a few (and now more because of this) i.e. Hardware Addicts, Ask Noah, pretty much all the podcast based ones).  So, thank you for taking your precious time (since I know you probably have a lot of other tasks with editing lots of shows) to build this!

So, I personally built something similar to this, because my [podcast player](https://castbox.fm/) doesn't have as robust of a playlist option as my [last one](http://www.beyondpod.mobi/). It does have timestamp comments though, which is why I stay with it.

So, I hacked around the playlist issue by creating a python api which accepted essentially an array of podcasts names and either a URL for an opml file or just a raw opml file through upload (probably a bit overkill for this, since you already have the rssmix.com setup (which is very cool and I'll have to check that out more)). Then it'll go out to each of the URLs, provided by the opml file, and grab the most 5 recent episodes from each show. Afterwards it'll take that list and store it in AWS s3 and also create a pre-signed link for accessing that info (just a bit more security, probably unnecessary for me but oh well :upside_down_face: ). I then plug that into a url shortener that I deployed before with s3 + route53 + cloudfront (which I modeled after [my work's](https://elrey.casa/work) (:arrow_left: example of short url)  process that they made). Below is an example of the web-ui that you get with python's FastAPI based on the code you write for your project.

![image](https://user-images.githubusercontent.com/10230166/146650240-47d2f345-6cd4-4d19-9aef-7743a4b41294.png)

I also had a bash script which would automate that last part (really easy to create), but my desktop has not been working (which is where the script is) and I haven't had time to get it fixed yet. So, I've been doing that last part manually about every month (which takes like 5 seconds).

I built the API this was for a few reasons:
1) I don't have to put a web server in front of it ( even though I do for adding TLS ) because the FastAPI project has a native web server when you run the script
2) I don't have to host the API externally (and wouldn't recommend it, because I didn't put auth in front of it), because the rss file is hosted on AWS s3
3) I can easily deploy it in a docker container, because everything is self contained (I pass in environment variables for AWS auth)
4) It only run's when I tell it to, so even with it inside a docker container it only uses a decent amount of resources when it goes to pull and process the lists from all the RSS feeds.
5) Once I have a particular group of podcasts that I don't want to change from it'll update the current s3 file (based on an md5sum of all the show names), so I can have a consistent s3 file
6) I don't use any local storage, because it all gets saved to s3 (which its like less than 75 cents per month (IIRC and most of that is from route53 (dns) costs) :upside_down_face: )
7) it's easy to automate, because it's just http requests (that you can use with bash and curl), because it's pretty simple to interface with
8) the code is self documenting with the docs page that I showed you above :upside_down_face: 

Here's [a link](https://github.com/elreydetoda/all-linux-tings/tree/master/apis/rssaggregator) to the folder with the project in it, but I don't have the best documentation yet :sweat_smile: . So, if your interested in using it, let me know and we can chat more about your particular use case + how my project could be modified to use it. If not I'm just going to leave it undocumented :upside_down_face: :sweat_smile: .  I could also probably do some Infrastructure as Code (Iac) (i.e. [terraform](https://www.terraform.io/) (which is how I currently deploy [jitsi on demand](https://gitlab.com/elreydetoda-infra/iac/misc/-/tree/master/apps/jitsi))) for the deployment process, so you have it documented how to deploy everything you need.

I will say, currently with my work we are really busy (lots of people trying to get a compliance checkbox by getting a pentest before the end of the year :sweat_smile: ), so I'd probably have to wait to modify the project for you till after the new year.

**Comment by MichaelTunnell** [comment]
thank you for sharing this but I forgot to mark this repo as an archive because this was replaced with a much better solution and the new solution does not use rssmix.

Here is the link to the new solution = https://github.com/MarkofCain/Multi_RSS_Combiner
