### ISSUE TITLE
[BUG] Missing Ask Noah Show

### ISSUE THREAD

**Issue by elreydetoda** [MichaelTunnell/dln-rss-merge#2]
Hey again (intro in #1) @MichaelTunnell, one thing that I noticed while listening to the all shows feed is that the Ask Noah Show isn't showing up in the feed. I noticed it a while back, but this was the first time I got a chance to let someone know about it.

I don't know exactly what's happening, but I was able to visibly confirm that you added his show to the all shows rssmix feed (image below). You can see Noah's show comes right before the DLN 256 in this feed.

http://www.rssmix.com/u/12005937/rss.xml

![image](https://user-images.githubusercontent.com/10230166/146653314-b97c9098-2966-4ac6-812a-8e9f5d66c588.png)

But, after it gets processed by this repo (at least I'd imagine that's how this repo works), it isn't showing up in the all shows feed on the DLN website. The image below shows that DLN extend actually come right before DLN 256.

https://destinationlinux.network/feed/allshows

![image](https://user-images.githubusercontent.com/10230166/146653320-8c67b8af-4fa5-4bd2-a783-69c2b6ec24d6.png)

I have no idea how php works, but let me know if you have any questions for me :slightly_smiling_face:

**Comment by MichaelTunnell** [comment]
This will not be fixed because this project is not in use. Sorry I forgot to mark this repo as an archive because this was replaced with a much better solution and the new solution does not use rssmix.

Here is the link to the new solution = https://github.com/MarkofCain/Multi_RSS_Combiner
